### ISSUE TITLE
[SP13] List Woo plugins installed on each private instance

### ISSUE THREAD

**Issue by zkan** [prontotools/pronto-woo-notifier#2]
As a developer, I want to see a list of Woo plugins installed on each private instance, so that I know which private instance has which Woo plugins installed.

**Exit Criteria**
- Show a list of Woo plugins installed on each private instance.
- Each Woo plugin in the list should contain name and version.

**Tasks**
- [x] Create plugin to wordpress to get all lastest woocommerce  plugin versions.
- [x] Create plugin to wordpress to get all commerce plugin and version that install for each PI site.
- [x] Make sync button and sync script to sync all lastest woocommerce plugin versions
- [x] Make sync button ans sync script to sync woocommerce plugin version for each PI site.
- [x] Create a page for list all woocommerce plugins page
- [x] Create a page for each site to show woocommerce plugins are installed for that site
